name: stagesDemo
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  Build:
    # Which image should my job run on? 
    # Could also be Windows 2019 (windows-2019) or macOS Monterey 12 (macos-12)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo This is my first stage!

  Test:
  
    needs: Build
    
    # Which image should my job run on? 
    # Could also be Windows 2019 (windows-2019) or macOS Monterey 12 (macos-12)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo This is my test stage!
  
  Prod:
    environment: validationFromOther
    needs: Test
    
    # Which image should my job run on? 
    # Could also be Windows 2019 (windows-2019) or macOS Monterey 12 (macos-12)
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo This is my test stage!
